#pragma once

#include "lemlib/api.hpp"
#include "lemlib/chassis/chassis.hpp"
#include "pros/adi.hpp"
#include "pros/distance.hpp"
#include "pros/imu.hpp"
#include "pros/motor_group.hpp"
#include "pros/optical.hpp"
#include "pros/rotation.hpp"

/**
 * @file globals.hpp
 * @brief Contains global variables and type definitions for the Robot
 * namespace.
 */

/**
 * @namespace Robot
 * @details In order to construct the robot, the Robot namespace is used to
 * contain all of the objects that are used to control the robot. This includes
 * the subsystems, methods, and global objects. We use PROS extensively for the
 * robot, it can be found at <A HREF="https://pros.cs.purdue.edu">PROS</A>
 * @authors Mori
 * @brief Contains all objects generated by the 6546E team - Contains all of the
 * subsystems, methods, and global objects.
 */

namespace Robot {
/**
 * @brief Contains global variables and type definitions for the Robot
 * namespace.
 * @details The majority of the global variables are defined in the Globals
 * namespace. This is to allow for easy access to the variables from any file in
 * the project. The Globals namespace is also used to hold lemlib objects that
 * are used to control the autonomous functions of the robot. It contains
 * parameters that are used to control the PID that lemlib uses, additionally.
 */

// 6 motor drivebase
// 2 motors elsewhere
// 1 pneumatic clamp
// 1 pneumatic doinker

// 2 rotational for odom
// 1 rotational for ladybrown
// 1 IMU
// 1 optical for color sort
// 1 distance for clamp


 namespace Globals {

    extern pros::Controller master;

    // Drivebase 
    extern pros::Motor LeftFront;
    extern pros::Motor LeftMid;
    extern pros::Motor LeftBack;
    extern pros::Motor RightFront;
    extern pros::Motor RightMid;
    extern pros::Motor RightBack;

    extern pros::MotorGroup drive_left;
    extern pros::MotorGroup drive_right;
    // Used as a motor group to be passed into lemlib, a full drivetrain
    extern lemlib::Drivetrain drivetrain;
    extern pros::MotorGroup drive_;


    // Other motor systems
    extern pros::Motor IntakeHookMotor;
    extern pros::Motor LadyBrownMotorMotor;


    // pneumatic Systems
    extern pros::adi::Pneumatics clampControl;
    extern pros::adi::Pneumatics goalSteal;

    // sensors
    extern pros::IMU inertial_sensor;
    extern pros::Rotation ladyBrownRotational;
    extern pros::Distance clamp_sensor;

    // color-related sorting
    extern pros::Optical colorSensor;
    

    // PID
    extern lemlib::ControllerSettings lateral_controller; // forward/back
    extern lemlib::ControllerSettings angular_controller; // turning


    // Odom
    extern lemlib::OdomSensors odomRotational;
    extern pros::Rotation lateral_sensor;
    extern pros::Rotation horizontal_sensor;

    // curvature
    extern lemlib::ExpoDriveCurve throttle_curve;
    extern lemlib::ExpoDriveCurve steer_curve;

    extern lemlib::Chassis chassis;

 } // namespace Globals
} // Namespace Robot
